swagger: '2.0'
info:
  description: "AccountSvc is not typically recommended for standard, single-tenant integrations. It adds an additional layer of complexity to your integration by circumventing the standard Admin Console experience. This makes Avalara’s ability to support the end customer more limited, and puts more of that support burden on the owner of the connector. For these reasons, we ask that you speak to a developer engineer directly before moving ahead with an AccountSvc integration. Using some resources in the AccountSvc API without sufficient understanding of the tax profile could result in serious tax liability issues for your client.

The AvaTax AccountSvc API allows you to interact with the company profile and admin console data on a given account. An integration that uses AccountSvc will still use GetTax to communicate with a company profile in the same way as one that does not use AccountSvc – the only difference will be the user experience in setting up that company profile.

*Note:* AccountSvc is currently accessible through the SOAP API only by using our .NET class library or building your own from WSDL. All requests must be authenticated with Account Admin level username/password credentials. The account number/license key credential pair cannot be used for AccountSvc."
  
  version: '1.0'
  title: AvaTax SOAP API
  termsOfService: 'http://www.avalara.com/terms/'
  contact:
    name: 'For support, visit the Avalara Community'
    url: 'https://community.avalara.com/avalara/category_sets/developers'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: development.avalara.net
basePath: /
schemes:
  - https
produces:
  - text/xml
consumes:
  - text/xml
x-ApiType: SOAP
x-wsdlPath: "https://development.avalara.net/Account/AccountSvc.wsdl"
x-basePath: "https://development.avalara.net/Account/AccountSvc.asmx"
paths:
  '/Account/AccountSvc.asmx?Ping':
    post:
      operationId: ping
      summary: Test service connectivity
      parameters:
        - in: header
          name: SOAPAction
          required: true
          description: 'SOAPAction must be "http://avatax.avalara.com/services/Ping" for this operation: e.g. `--header "SOAPAction: \"http://avatax.avalara.com/services/Ping\""`'
          x-example: "http://avatax.avalara.com/services/Ping"
          type: string
        - in: body
          name: Envelope
          schema:
            $ref: '#/definitions/PingEnvelope'
      responses:
        '200':
          description: 'The operation was completed. Refer to the response property `ResultCode` to determine operation success or error.'
          schema: 
            $ref: '#/definitions/PingResponse'
        '400':
          description: 'An Error Occurred. Check the error message text to find more information.'
          schema:
            $ref: '#/definitions/UnauthorizedError'
  '/Account/AccountSvc.asmx?IsAuthorized':
    post:
      operationId: isAuthorized
      summary: Test authorized operations
      parameters:
        - in: header
          name: SOAPAction
          required: true
          x-example: "http://avatax.avalara.com/services/IsAuthorized"
          description: 'SOAPAction must be "http://avatax.avalara.com/services/IsAuthorized" for this operation: e.g. `--header "SOAPAction: \"http://avatax.avalara.com/services/IsAuthorized\""`'
          type: string
        - in: body
          name: Envelope
          schema:
            $ref: '#/definitions/IsAuthorizedEnvelope'
      responses:
        '200':
          description: 'The operation was completed. Refer to the response property `ResultCode` to determine operation success or error.'
          schema: 
            $ref: '#/definitions/IsAuthorizedResponse'
        '400':
          description: 'An Error Occurred. Check the error message text to find more information.'
          schema:
            $ref: '#/definitions/UnauthorizedError'
definitions:
  PingEnvelope:
    xml:
      name: Envelope
      prefix: SOAP-ENV
      namespace: "http://schemas.xmlsoap.org/soap/envelope/"
    required:
      - Header
      - Body
    properties:
      Header:
        $ref: '#/definitions/Header'
      Body:
        $ref: '#/definitions/PingBody'
  PingBody:
    xml:
      name: Body
      prefix: SOAP-ENV
    required:
      - Ping
    properties:
      Ping:
        $ref: '#/definitions/Ping' 
  IsAuthorizedEnvelope:
    xml:
      name: Envelope
      prefix: SOAP-ENV
      namespace: "http://schemas.xmlsoap.org/soap/envelope/"
    required:
      - Header
      - Body
    properties:
      Header:
        $ref: '#/definitions/Header'
      Body:
        $ref: '#/definitions/IsAuthorizedBody'
  IsAuthorizedBody:
    xml:
      name: Body
      prefix: SOAP-ENV
    required:
      - IsAuthorized
    properties:
      IsAuthorized:
        title: IsAuthorized
        xml:
          namespace: "http://avatax.avalara.com/services"
        type: object
        properties: 
          IsAuthorizedRequest:
            $ref: '#/definitions/IsAuthorizedRequest' 
  CompanyContactFetchEnvelope:
    xml:
      name: Envelope
      prefix: SOAP-ENV
      namespace: "http://schemas.xmlsoap.org/soap/envelope/"
    required:
      - Header
      - Body
    properties:
      Header:
        $ref: '#/definitions/Header'
      Body:
        $ref: '#/definitions/IsAuthorizedBody'
  Ping:
    xml:
      namespace: "http://avatax.avalara.com/services"
    required:
      - Message
    properties:
      Message:
        type: string
        description: "A message recorded in server-side audit logs. Can be empty."
        maxLength: 255
  IsAuthorizedRequest:
    required:
      - Operations
    properties:
      Operations:
        type: string
        maxLength: 255
        description: "The list of operations that you would like to test."
  ResultCode:
    type: string
    example: Success
    description: 'Classifies severity of message. One of: Success, Warning, Error, Exception'
  UnauthorizedError:
    xml:
      name: Envelope
      prefix: s
      namespace: "http://schemas.xmlsoap.org/soap/envelope/"
    properties:
      Body:
        title: Body
        type: object
        xml:
          prefix: s
        properties:
          Fault:
            title: Fault
            type: object
            xml:
              prefix: s
            properties:
              faultcode:
                type: string
                example: 's:Client'
              faultstring:
                type: string
                example: 'The user or account could not be authenticated.'
  Message:
    xml:
      name: Message
    properties:
      Summary:
        maxLength: 255
        type: string
        example: Company not found.  Verify the CompanyCode.
        description: The message summary in short form.
      Details:
        maxLength: 255
        type: string
        example: APITrialCompany
        description: Description of the error or warning.
      RefersTo:
        maxLength: 255
        type: string
        example: CompanyCode
        description: The data used during the request that caused the message to be generated.
      Source:
        maxLength: 255
        type: string
        example: Avalara.AvaTax.Services.Tax
        description: The internal location that generated the message.
      Severity:
        type: string
        example: Error
        description: "Classifies the severity of the message. One of: Success, Warning, Error, Exception."
  PingResponse:
    description: Result data returned from Ping.
    properties:
      PingResult:
        type: object
        title: PingResult
        xml: 
          namespace: "http://avatax.avalara.com/services"
        properties: 
          Version:
            description: The service version of the AvaTax service.
            maxLength: 15
          TransactionId:
            type: string
            maxLength: 19
            description: The unique transaction ID assigned by AvaTax to this request/response set. This value need only be retained for troubleshooting.
          ResultCode:
            $ref: '#/definitions/ResultCode'
          Messages:
            type: array
            xml: 
              wrapped: true
            items:
              $ref: '#/definitions/Message'
  IsAuthorizedResponse:
    description: Result data returned from IsAuthorized.
    properties:
      IsAuthorizedResult:
        title: IsAuthorizedResult
        type: object
        xml:
          namespace: "http://avatax.avalara.com/services"
        properties:
          Expires:
            description: The date and time at which your AvaTax account will expire. DateTime in the format YYYY-MM-DD
            type: string
            maxLength: 10
          Operations:
            type: string
            description: "The operations that the current user is authorized to use. Determined from the list provided in the IsAuthorized call. Possible operations are: Ping, IsAuthorized, GetTax, PostTax, CommitTax, CancelTax, AdjustTax, GetTaxHistory, Validate."
            maxLength: 255
          TransactionId:
            type: string
            maxLength: 19
            description: The unique transaction ID assigned by AvaTax to this request/response set. This value need only be retained for troubleshooting.
          ResultCode:
            $ref: '#/definitions/ResultCode'
          Messages:
            type: array
            xml:
              wrapped: true
            items:
              $ref: '#/definitions/Message'
  FetchRequest:
    properties:
      Fields:
        description: "Allows the user to specify which properties of the specified object are desired. If not populated, all fields at the root level will be returned. Default and optional fields are documented at the operation level."
        type: string
      Filters:
        description: "Allows the user to specify filter criteria for the result set. e.g. to return all batches with BatchId=12345, the filter would be 'BatchId=12345'. Not required, but highly recommended"
        type: string
      Sort:
        description: "Returns the records sorted by the specified field. Especially useful when used with RecordCount."
        type: string
      MaxCount:
        description: "Maximum number of records to be returned"
        type: number
        format: integer
      PageIndex:
        description: "PageIndex and PageSize (along with Sort) allow for pagination of records. PageIndex will determine the page number returned, as determined by Sort and PageSize from the result set."
        type: number
        format: integer
      PageSize:
        description: "See PageIndex."
        type: number
        format: integer
      RecordCount:
        description: "Specifies the maximum number of records to be returned. Note that there is a service-level RecordCount limit of 100,000."
        type: number
        format: integer
  FilterRequest:
    properties:
      Filters:
        description: "Allows the user to specify filter criteria for the result set. e.g. to return all batches with BatchId=12345, the filter would be 'BatchId=12345'. Not required, but highly recommended"
        type: string
      MaxCount:
        description: "Maximum number of records to be returned"
        type: number
        format: integer
  FilterResult:
    properties:
      RecordCount:
        description: "The number of records found that fit the filter criteria specified in the request."
        type: number
        format: integer
      TransactionId:
        type: string
        maxLength: 19
        description: The unique transaction ID assigned by AvaTax to this request/response set. This value need only be retained for troubleshooting.
      ResultCode:
        $ref: '#/definitions/ResultCode'
      Messages:
        type: array
        xml:
          wrapped: true
        items:
          $ref: '#/definitions/Message'
  Header:
    description: 'The SOAP API uses standard WSS (Web Service Security) token to authenticate the account or user, and additional `Profile` information to describe the agent calling the service.'
    required:
      - Security
      - Profile
    properties:
      Security:
        $ref: '#/definitions/Security'
      Profile:
        $ref: '#/definitions/Profile'
    xml:
      prefix: 'SOAP-ENV'
  Security:
    required:
      - UsernameToken
    properties:
      UsernameToken:
        $ref: '#/definitions/UsernameToken'
      'SOAP-ENV:actor':
        type: string
        example: "http://schemas.xmlsoap.org/soap/actor/next"
        description: 'The WS-Security standard requires the wsse:Security element contains a SOAP-ENV:actor attribute.'
        xml:
          attribute: true
    xml:
      prefix: 'wsse'
      namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
  UsernameToken:
    description: Either an Account/LicenseKey or a Username/Password is required to authenticate the request. AccountNumber/LicenseKey is preferred.
    xml:
      prefix: 'wsse'
    required:
      - Account
      - LicenseKey
    properties:
      Account:
        type: string
        maxLength: 10
        description: The unique account number provided by Avalara for verification against the service. If you are on a free trial and don’t have a license key, use Username.
        example: 1234567890
        xml:
          prefix: 'wsse'
      LicenseKey:
        type: string
        maxLength: 16
        description: The unique alpha-numeric key provided by Avalara for verification against the service. If you are on a free trial and don’t have a license key, use Password.
        example: A1B2C3D4E5F6G7H8
        xml:
          prefix: 'wsse'
      Username:
        type: string
        maxLength: 50
        description: Your AvaTax Admin Console username. Usually an email address.
        xml:
          prefix: 'wsse'
      Password: 
        type: string
        maxLength: 50
        description: Your AvaTax Admin Console password.
        xml:
          prefix: 'wsse'
  Profile: 
    required:
      - Client
      - Adapter
      - Name
      - Machine
    xml:
      namespace: 'http://avatax.avalara.com/services'
    properties:
      Client: 
        type: string
        maxLength: 50
        description: 'Client application name and version. This should unique identify the software client that is calling the AvaTax service, and should be consistent across all deployments of that client version. e.g. “Drupal Commerce 5.7”'
      Adapter: 
        type: string
        maxLength: 50
        description: Name and version of the adapter. This is set automatically by the .NET, PHP, and Java adapters.
      Machine:
        type: string
        maxLength:  50
        description: The NetBIOS name of the local computer. This is set automatically by the .NET, PHP, and Java adapters.
      Name:
        type: string
        maxLength: 50
        description: Reference to a named profile.
  UnauthorizedError:
    xml:
      name: Envelope
      prefix: s
      namespace: "http://schemas.xmlsoap.org/soap/envelope/"
    properties:
      Body:
        title: Body
        type: object
        xml:
          prefix: s
        properties:
          Fault:
            title: Fault
            type: object
            xml:
              prefix: s
            properties:
              faultcode:
                type: string
                example: 's:Client'
              faultstring:
                type: string
                example: 'The user or account could not be authenticated.'